spring:
  application:
    name: ms-auth-kyc
  security:
    oauth2:
      client:
        registration:
          pin-client:
            client-id: pin-client
            client-secret: ${CLIENT_SECRET_KEYCLOAK}
            authorization-grant-type: authorization_code
            redirect-uri: "http://192.168.0.196:8020/auth/login/oauth2/code/pin-client"
            scope:
              - openid
              - profile
              - email
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/pin-realm
  profiles:
    active: mock

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

