spring:
  application:
    name: ms-auth-kyc
  profiles:
    active: mock
  config:
    import: "classpath:application-vault.yml,vault://"
  security:
    oauth2:
      client:
        registration:
          pin-client:
            client-id: ${client-id}
            client-secret: ${client-secret}
            authorization-grant-type: ${grant-type}
            redirect-uri: ${redirect-uri}
            scope:
              - openid
              - profile
              - email
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: ${issuer-uri}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 0

eureka:
  instance:
    hostname: 192.168.0.195
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${eureka-server}